## Secrets necesarios
# HUB_DOCKER_USERNAME
# HUB_DOCKER_PASSWORD
# SONAR_TOKEN
# GITHUB_TOKEN

name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
ENV:
jobs:
  sendSonar:
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # JDK 11 para Sonar
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      # Envío Sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$GITHUB_REPOSITORY
  build_and_test_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # JDK 8 para build
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      # Package con Maven
      - name: Build project with Maven
        run: ./mvnw -B package -Pjib -Djib.to.auth.username=${{ secrets.HUB_DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.HUB_DOCKER_PASSWORD }}