## Secrets necesarios
# HUB_DOCKER_USERNAME
# HUB_DOCKER_PASSWORD
# SONAR_TOKEN
# GITHUB_TOKEN

name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  sendSonar:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[sonar skip]')"
    steps:
      # Checkout
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # JDK 11 para Sonar
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Envío Sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=orders-service-obligatorio -Dsonar.organization=obligatorio-devops-2021 -Dsonar.host.url="https://sonarcloud.io"
  build_and_test_and_push:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    permissions:
      contents: read
      packages: write
    steps:
      # Checkout
      - uses: actions/checkout@v2
      # JDK 8 para build
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # Package with Maven & jib profile to build & push docker image
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'Github Release'
          email: 'release@github.com'
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Build project with Maven
        run: ./mvnw -B "
      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          git-release-bot-name: "Github-Release"
          git-release-bot-email: "release@github.com"
          maven-args: "-Pjib -Darguments=\"-Djib.to.auth.username=${{ secrets.HUB_DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.HUB_DOCKER_PASSWORD }}\""
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
