name: CI Build
on: never
jobs:
  QUALITY_GATES_AND_TEST:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[sonar skip]')"
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: "https://sonarcloud.io"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "sonar-project.properties"
          FILE_DATA: >
            sonar.projectKey=orders-service-obligatorio
            sonar.organization=obligatorio-devops-2021
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 10